### ISSUE TITLE
テストカバレッジとCI/CDパイプライン構築の提案

### ISSUE THREAD

**Issue by takutakahashi** [kommon-ai/agent-mcp-server#6]
## テストカバレッジ向上とCI/CDパイプライン構築の提案

現状ではテストコードがなく、CI/CDの設定も見当たりません。これらを追加することで、コードの品質向上と開発プロセスの改善を図ることを提案します。

#### 1. テストフレームワークの追加

- 単体テスト: 各関数、メソッドのテスト
- 統合テスト: サーバーの起動とAPIリクエストのテスト
- モック: 外部依存関係（GitHub API、OpenRouter API）のモック

#### 2. CI/CDパイプラインの構築

GitHub Actionsを使用した自動化パイプラインを実装し、以下を含めます：

- コードビルド
- テスト実行
- コードカバレッジレポート生成
- リンターによる静的解析
- 自動リリース生成

### テストフレームワーク例

```go
// pkg/goosemcp/tools_test.go
package goosemcp

import (
	"os"
	"testing"
)

func TestNewGooseTool(t *testing.T) {
	// ツール作成のテスト
	tool := NewGooseTool()
	
	if tool == nil {
		t.Errorf("NewGooseTool() returned nil")
	}
	
	// ツール名のテスト
	if tool.Tool.Name != "goose-run" {
		t.Errorf("Expected tool name to be 'goose-run', got '%s'", tool.Tool.Name)
	}
}

func TestToolExecution(t *testing.T) {
	// 環境変数のモック
	os.Setenv("OPENROUTER_API_KEY", "test-key")
	os.Setenv("GITHUB_TOKEN", "test-token")
	defer func() {
		os.Unsetenv("OPENROUTER_API_KEY")
		os.Unsetenv("GITHUB_TOKEN")
	}()
	
	tool := NewGooseTool()
	
	// 有効な入力でのテスト
	args := map[string]interface{}{
		"name":   "test-agent",
		"prompt": "test-prompt",
		"repo":   "test-repo",
	}
	
	// TODO: 実際のエージェント呼び出しをモック化
	// result := tool.Handler(args)
	// assertエージェント結果
}

func TestErrorHandling(t *testing.T) {
	tool := NewGooseTool()
	
	// 無効な入力でのテスト
	args := map[string]interface{}{
		// "name" is missing
		"prompt": "test-prompt",
		"repo":   "test-repo",
	}
	
	result := tool.Handler(args)
	
	// エラーチェック
	if result.IsError == nil || !*result.IsError {
		t.Errorf("Expected error for missing required field")
	}
}
```

### CI/CDパイプライン例

```yaml
# .github/workflows/ci.yml
name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23.x
    
    - name: Install dependencies
      run: go mod download

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      
    - name: Test
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.txt

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23.x
    
    - name: Build
      run: go build -v ./...
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          agent-mcp-server
```

### メリット

- 品質の向上: テストによるバグの早期発見
- 安心感のある変更: 既存機能を壊していないことを確認
- 継続的な開発: プロジェクトの長期的な維持をサポート
- コミュニティ貢献の促進: 貢献者がプロジェクトの品質基準を理解しやすい

テストカバレッジとCI/CDパイプラインは、プロジェクトの品質と持続可能性を高めるための重要な要素です。この提案が採用された場合、実装のサポートも可能です。
